### ISSUE TITLE
Carousel js won't work i < 9

### ISSUE THREAD

**Issue by dcnb** [CollectionBuilder/collectionbuilder-contentdm#13]
I've had this happen before with smaller collections. But the include/carousel-js won't work if the number of carouselItems is fewre than 9, which is the top number in the javascript for loop. 

We should add a failsafe in there that counts the items and if it's less than 9, drops it down to that number. I don't know if we should do that with javascript or liquid (probably javascript, I'm assuming).

**Comment by evanwill** [comment]
should be fixed with 91338b38f3be808b194fd83a2b6bb72c2b33668e
