### ISSUE TITLE
cloud-js --> Should subjects min requirement be >= rather than >

### ISSUE THREAD

**Issue by dcnb** [CollectionBuilder/collectionbuilder-contentdm#14]
Right now our uniq terms are requiring the terms to be used more than the subject minimum 

{%- assign uniqTerms = terms | downcase | split: ";" | array_count_uniq | sort | where_exp: 't','t[1] > site.data.theme.subjects-min' -%}

But I think it should more or equal to 

{%- assign uniqTerms = terms | downcase | split: ";" | array_count_uniq | sort | where_exp: 't','t[1] >= site.data.theme.subjects-min' -%}

Any reason not to do that? I don't think folks are going to put 0 as a subject-min in the theme.

**Comment by evanwill** [comment]
this is fixed in a8052b58da8217f844aa61acfa1cab996b4771ce 

but it looks like 
`{%- assign uniqTerms = terms | downcase | split: ";" | array_count_uniq | sort | where_exp: 't','t[1] >= termsMin' -%}` 
in cloud-js.html

are you looking at collectionbuilder-cdm-template?

**Comment by evanwill** [comment]
oh, @dcnb i see you were looking at uwt-cpd, which doesn't have the newest cloud-js stuff from master...
