### ISSUE TITLE
feature: Nav drop down

### ISSUE THREAD

**Issue by evanwill** [CollectionBuilder/collectionbuilder-contentdm#29]
in config-nav.csv option to create drop downs with parent. 
example, About with multiple content pages, multiple clouds, etc.

**Comment by owikle** [comment]
I already did this in ijc_draft, but I'm not sure if it's the smoothest way to do it: https://github.com/uidaholib/ijc_draft/commit/44eb1e46bae7587fe5490e94e3f2b5de99675dc2

**Comment by evanwill** [comment]
I am trying a bit simplified approach, in branch dropdown-nav, draft: 97b7ead0677a937d5cb9455c5077e2caa9b0a52d

basically just following a convention in config-nav:
- if the item has a stub, but no value in parent, it becomes a normal nav item
- if the item has NO stub, it will become a dropdown button
- if the item has a value in parent, it will only show up under the parent dropdown 

Not sure how to make the drop down show up as active item exactly (the drop down item does, but not the dropdown button).

**Comment by evanwill** [comment]
I figured out how to make the dropdown show up as active, 8e82b62e6d0f330da133e5bfd67787cb6e22ca63

@dcnb @owikle I don't know, I still think bootstrap dropdowns look kind of terrible... 
but let me know if you think that this arrangement of config-nav is intuitive, 

or maybe if you would rather explicitly say the item is a parent (maybe just `true` in parent column?) rather than leaving stub empty.

ALSO-- anyone remember why we have `mt-1` on every nav item?? It doesn't seem to be necessary?
