### ISSUE TITLE
problem with "Greater than" in cloud.js

### ISSUE THREAD

**Issue by dcnb** [CollectionBuilder/collectionbuilder-contentdm#34]
where_exp: 't','t[1] > termsMin'

Shouldn't this be greater or equal to? 

I think the theme is confusing if it says minimum but then doesn't show up

**Comment by evanwill** [comment]
are you working from an out-of-date branch?
i fixed that
https://github.com/CollectionBuilder/collectionbuilder-contentdm/blob/master/_includes/js/cloud-js.html

last time you assigned it to me! :wink: 
a8052b58da8217f844aa61acfa1cab996b4771ce

**Comment by dcnb** [comment]
I followed the installation instructions on the website. So I must have had
an outdated version.

Time for 1.03, I'd think.

**Comment by evanwill** [comment]
The release still matches what is in the documentation--we need to be ready to update docs for a new release, since some of the config has changed. Probably wait until i rewrite the cloud layout
