### ISSUE TITLE
webrick missing from ruby 3.0.0

### ISSUE THREAD

**Issue by jennrandles** [CollectionBuilder/collectionbuilder-contentdm#52]
I'm following the [guide to set up](https://collectionbuilder.github.io/docs/repository.html) and have run into an issue. I installed the latest stable version of Ruby 3.0.0 and get this message when trying to generate my site via jekyll s in terminal:

/Users/jrandles/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/commands/serve/servlet.rb:3:in `require': cannot load such file -- webrick (LoadError)

Looks like webrick isn't included in Ruby 3.0.0- Should I roll back to 2.7.0? I tried `bundle add webrick` but it doesn't work either. I get `Could not locate Gemfile`. Is there a specific directory I need to be in for that command?

**Comment by evanwill** [comment]
@jrandlestsla I haven't had a chance to look closely yet--but seems to be a Ruby 3.0 thing that is hitting Jekyll community--and still waiting for them to sort it all out. Unfortunately, we haven't tested it out yet, but it is related to Jekyll, not collectionbuilder in particular. 
In the meantime: 

People are reporting fixing it with `bundle add webrick`.
You need to run that command in the root folder of your collectionbuilder project. For example, if I was doing it for this repository, I would run it with the terminal open in the "collectionbuilder-contentdm" folder, which would add webrick to the [Gemfile in the project](https://github.com/CollectionBuilder/collectionbuilder-contentdm/blob/main/Gemfile), then triggers a new bundle install. Each Gemfile is specific to the project, and manages the bundle for that project only, not your global Ruby environment. 

So first option to try is `bundle add webrick` in your project folder. Then use the command `bundle exec jekyll s` to serve it. (this should work *in theory*!)

Second option, is to change your Ruby version using rbenv, going back to 2.7 (which we have been using):

1. install the older version of Ruby using: `rbenv install 2.7.2`
2. set that version as the default: `rbenv global 2.7.2`
3. install Jekyll again with the new ruby: `gem install jekyll bundler` 
4. in your collectionbuilder project: `bundle install`
5. in your collectionbuilder project: `bundle exec jekyll s`

Let me know if either of these work! 
I will dive into Ruby 3.0 and update docs or Gemfile once we figure out the implications. 
Thanks!

**Comment by jennrandles** [comment]
Thanks! I ran the command in the project folder and it worked.

**Comment by evanwill** [comment]
@dcnb @owikle there is a fix in Jekyll merged in January, but not included in current version 4.2.0 (released in Dec)--so the problem will go away soon-ish I would think. 
Jekyll 4.2.0 was released Dec 14, 2020. Ruby 3.0 became "stable" Dec 25, 2020. So if you were starting from fresh, installing from our docs since Dec 25, you would be impacted by this.

Do we want to add a mention of "`bundle add webrick` if you are on Ruby 3.0 and having issues" to the docs?

Or add webrick to the repository Gemfile? (maybe temporarily until next version of jekyll is released--i don't think there is a big negative to this, just weird possibilities of getting a version of webrick locked down separate from Jekyll's dependencies)
Or maybe have people install webrick when installing gems `gem install bundler jekyll webrick`), since without that they won't be able to use `jekyll s` anywhere without bundling first?

**Comment by evanwill** [comment]
I added a warning note in the CB Docs, https://collectionbuilder.github.io/docs/software.html#jekyll

**Comment by dcnb** [comment]
I think we should just add webrick to the Gemfile. 

but the real question is, is it web brick or web Rick? what a tricky name ...

**Comment by evanwill** [comment]
yeah, I am not quite sure. 
One prob with just adding to Gemfile is that no where in the docs do we say to `bundle install` or `bundle exec jekyll s`, so they still run into the issue and then have to figure out to `bundle install`. 

So it pushes us to update docs quite a bit and have a more formal use bundle approach--and if we are telling people to bundle install, then we may as well have more specific requirements in the Gemfile to make sure everything works--and then your global jekyll doesn't work, so we need to make sure people know what the Gemfile is actually all about, and if we are doing that then maybe we don't mention installing jekyll at all, you just have a Gemfile and `bundle install` instead... :crying_cat_face: 

I am surprised by how little chatter there is about the issue--I guess probably not many people have installed ruby 3 yet?

**Comment by evanwill** [comment]
Actually, another simple approach: update docs to say "ruby 3 recently came out, but we suggest sticking with 2.7 for now".

RubyInstaller for Windows is still suggesting 2.7 at this point anyway.

**Comment by evanwill** [comment]
this issue is now addressed in Gemfiles and the new docs, https://collectionbuilder.github.io/cb-docs/ , so closing this issue. thanks!
